#!/bin/sh

sudo /etc/init.d/apache2 stop
sudo /etc/init.d/postgresql stop
sudo /etc/init.d/timidity stop
sudo /etc/init.d/lastfmsubmitd stop
sudo /etc/init.d/cups stop
sudo /etc/init.d/dictd stop
sudo /etc/init.d/postfix stop
sudo /etc/init.d/portmap stop
sudo /etc/init.d/privoxy stop
sudo /etc/init.d/virtualbox stop
sudo /etc/init.d/ntop stop
sudo /etc/init.d/nfs-kernel-server stop
sudo /etc/init.d/openipmi stop
sudo /etc/init.d/openbravo stop
sudo /etc/init.d/apparmor stop
sudo /etc/init.d/anacron stop
sudo /etc/init.d/cron stop
sudo /etc/init.d/collectd stop
sudo /etc/init.d/saned stop
sudo /etc/init.d/mpd stop
sudo /etc/init.d/rsync stop
sudo /etc/init.d/virtuoso-nepomuk stop
sudo /etc/init.d/bluetooth stop
sudo /etc/init.d/dcmqrscp stop
sudo /etc/init.d/ebtables stop
sudo /etc/init.d/ssh stop
sudo /etc/init.d/statd stop
sudo /etc/init.d/sysstat stop
sudo /etc/init.d/storescp stop
sudo /etc/init.d/sphinxsearch stop
sudo /etc/init.d/smartmontools stop
sudo /etc/init.d/speech-dispatcher stop
sudo /etc/init.d/winbind stop
sudo /etc/init.d/unattended-upgrades stop
sudo /etc/init.d/libvirt-bin stop
sudo /etc/init.d/atd stop
sudo /etc/init.d/avahi-daemon stop
sudo /etc/init.d/network-manager stop
sudo /etc/init.d/networking stop
